services:
  postgres:
    image: postgres:16
    container_name: music_metadata_postgres
    environment:
      POSTGRES_DB: music_metadata
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: