"""create tracks table

Revision ID: a38c470f1289
Revises: 
Create Date: 2026-09-01 15:33:53.635505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38c470f1289'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('normalized_artist', sa.String(length=255), nullable=True),
    sa.Column('normalized_title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_isrc'), 'tracks', ['isrc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_isrc'), table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
